%include	/usr/lib/rpm/macros.perl
Summary:	Nagios to RRD
Name:		nagios-n2rrd
Version:	1.3.2
Release:	0.1
License:	GPL v2
Group:		Applications
Source0:	http://n2rrd.diglinks.com/download/n2rrd-%{version}.tar.gz
# Source0-md5:	503dabbc89e1e4f73e5892faf0b41c9d
URL:		http://n2rrd.diglinks.com/
BuildRequires:	rpm-perlprov >= 4.1-13
BuildRequires:	sed >= 4.0
Requires:	nagios-common
BuildArch:	noarch
BuildRoot:	%{tmpdir}/%{name}-%{version}-root-%(id -u -n)

%define		_sysconfdir		/etc/n2rrd
%define		nagiosconfdir	/etc/nagios
%define		nagiosdatadir	/usr/share/nagios
# argh XXX lib64?
%define		nagioslibdir	/usr/lib/nagios
%define		nagioscgidir	%{nagioslibdir}/cgi

%description
N2RRD is an Nagios add-on tool, which stores performance data
generated by Nagios plugins into RRD database. The package also
includes display tool rrd2graph to view data stored in RRD database.

%prep
%setup -q -n n2rrd-%{version}

for fdist in $(find templates -name dist-*); do
	fnew=`echo $fdist | sed 's/dist-//'`
	mv $fdist $fnew
done

%{__sed} -i -e '1s,#!@BIN_PERL@,#!%{__perl} -w,' *.pl *.cgi
%{__sed} -i -e 's,@CGIBIN@,%{nagioscgidir},' js/zoom.js

cat > README.PLD <<'EOF'
Edit %{nagiosconfdir}/nagios.cfg to reflect the following variables

process_performance_data=1
host_perfdata_command=%{nagioslibdir}/process-host-perfdata-n2rrd
service_perfdata_command=%{nagioslibdir}/process-service-perfdata-n2rrd

Read more about how to integrate from:
<http://n2rrd.diglinks.com/cgi-bin/trac.cgi/wiki/InstallationGuide>.
EOF

cat > nagios.conf <<'EOF'
define command {
	command_name    process-host-perfdata-n2rrd
	command_line	%{nagioslibdir}/n2rrd -c %{_sysconfdir}/n2rrd.conf -T $LASTHOSTCHECK$ -H $HOSTNAME$ -s "check_ping" -o "$HOSTOUTPUT$"
}
define command {
	command_name    process-service-perfdata-n2rrd
	command_line	%{nagioslibdir}/n2rrd -c %{_sysconfdir}/n2rrd.conf -T $LASTSERVICECHECK$ -H $HOSTNAME$ -s "$SERVICEDESC$" -o "$SERVICEPERFDATA$"
}
EOF

%install
rm -rf $RPM_BUILD_ROOT
install -d $RPM_BUILD_ROOT{%{_sysconfdir},%{_examplesdir}/%{name}-%{version}}
cp -a n2rrd.conf $RPM_BUILD_ROOT%{_sysconfdir}
# we provide templates as examples
cp -a templates $RPM_BUILD_ROOT%{_examplesdir}/%{name}-%{version}
# provide only directory structure
install -d $RPM_BUILD_ROOT%{_sysconfdir}/templates/{maps,graph,rewrite,rra,code}

install -d $RPM_BUILD_ROOT{%{nagioslibdir},%{nagiosconfdir}/plugins,%{nagioscgidir},%{nagiosdatadir}/js}
install n2rrd.pl $RPM_BUILD_ROOT%{nagioslibdir}/n2rrd
cp -a nagios.conf $RPM_BUILD_ROOT%{nagiosconfdir}/plugins/n2rrd.conf
install rrd2graph.cgi $RPM_BUILD_ROOT%{nagioscgidir}
cp -a js/zoom.js $RPM_BUILD_ROOT%{nagiosdatadir}/js

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(644,root,root,755)
%doc CHANGELOG UPGRADE README.PLD
%dir %{_sysconfdir}
%{_sysconfdir}/templates
%config(noreplace) %verify(not md5 mtime size) %{_sysconfdir}/n2rrd.conf
%config(noreplace) %verify(not md5 mtime size) %{nagiosconfdir}/plugins/n2rrd.conf
%attr(755,root,root) %{nagioscgidir}/rrd2graph.cgi
%attr(755,root,root) %{nagioslibdir}/n2rrd
%dir %{nagiosdatadir}/js
%{nagiosdatadir}/js/zoom.js
%{_examplesdir}/%{name}-%{version}
